### ISSUE TITLE
kernel_route: Invalid argument

### ISSUE THREAD

**Issue by scientificworld** [jech/babeld#100]
Hi, I'm using babeld 1.10 which is from yum on CentOS 7 (kernel version 3.10.0-1160.49.1.el7.x86_64).
When I see the log of systemctl, I find that it keeps outputing `kernel_route(ADD): Invalid argument` and `kernel_route(MODIFY metric): Invalid argument`.
Is there any way to fix it without upgrading the kernel? Thank you.

**Comment by jech** [comment]
Difficult to tell.  Perhaps you could run babeld with the flag '-d2' in order to find out which operation triggers the error?  Beware, it will generate massive amounts of logs.
