### ISSUE TITLE
Babeld does not function properly

### ISSUE THREAD

**Issue by zhangmazi123321** [jech/babeld#103]
I configured the NIC following the steps given. However, the following prompt appears when executing the last command.

zhangmazi@zhangmazi-virtual-machine:~$ sudo iwconfig wlx90de8074df25 mode ad-hoc channel 1 essid "my-mesh"
zhangmazi@zhangmazi-virtual-machine:~$ sudo ip link set up dev wlx90de8074df25
zhangmazi@zhangmazi-virtual-machine:~$ sudo ip addr add 192.168.13.2 dev wlx90de8074df25
zhangmazi@zhangmazi-virtual-machine:~$ sudo ip -6 addr add $(generate-ipv6-address -r)/128 dev wlx90de8074df25
zhangmazi@zhangmazi-virtual-machine:~$ sudo babeld wlx90de8074df25
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address
send: Cannot assign requested address

 Can you give some advice?

**Comment by jech** [comment]
Do this:
```
ip -6 addr add $(generate-ipv6-address fe80::) dev wlx90de8074df25
```
This is described in the README file under *A note about tunnels and VPNs*.
