### ISSUE TITLE
babeld improvement opportunities

### ISSUE THREAD

**Issue by drozdziak1** [jech/babeld#12]
Hello,
first of all, **kudos for creating this project!** 

Recently I got myself into contributing to Althea's [fork](https://github.com/althea-mesh/babeld) of `babeld` and found some places around the upstream codebase that might hold potential for improvements. **But on the other hand, maybe there's code which I simply don't understand**, hence this issue. I'd really appreciate it if you could share your thoughts on this. Thank you!

## Ring buffers in format functions
* **What:** The `format*` functions in `util.h` use static ring buffers for holding 4 last return values, e.g.:
```c
const char *
format_thousands(unsigned int value)
{
    static char buf[4][15]; // I mean buffers like this one
    static int i = 0;
    i = (i + 1) % 4;
    snprintf(buf[i], 15, "%d.%.3d", value / 1000, value % 1000);
    return buf[i];
}
```
* **Why:** This doesn't really help with anything and could cause printing bugs that are termendously difficult to catch.
* **How:** A very common and battle-tested approach is to have the user supply their own, e.g.:
```c
char *
format_thousands(unsigned int value, char *buf, size_t buflen)
{
    if (!buf) {
        if (!buflen) {
        /* They don't supply the buffer and specify a 0 size, therefore we're allocating it for them. 
         * This of course is optional as we could simply return NULL whenever !buf holds true
         */
            buf = malloc(15);
            buflen = 15;
        } else {
            return NULL; // They don't give us a valid buffer and yet define the length.
        }
    }
    snprintf(buf, buflen, "%d.%.3d", value / 1000, value % 1000);
    return buf;
}
```

## Many pointers are not null-checked and some symbols are not used
* **What:** In some functions around the codebase pointer sanity is not checked, e.g.:
```c
static int
kernel_rule_notify(struct kernel_rule *rule, void *closure) // closure is not used
{
    int i;
    if(martian_prefix(rule->src, rule->src_plen)) // Risky business, rule could be NULL
        return 0;

    i = rule->priority - src_table_prio;

    if(i < 0 || SRC_TABLE_NUM <= i)
        return 0;

    kernel_rules_changed = 1;
    return -1;
}
```
* **Why:**  It's a common practice to explicitly react to null pointers where there should be process-owned memory. Many developers expect this and it's also smart to put error logging in the event of an unexpected `NULL` pointers occurring
* **How:** Let's just surround all pointer parameters with if statements that check if they're `NULL`

**Comment by jech** [comment]
> The format* functions in util.h use static ring buffers for holding 4 last return values

These are just debugging functions.  I don't see any way to fix that without complicating the debugging code.

> Let's just surround all pointer parameters with if statements that check if they're NULL

If this pointer is null, that would point to a bug elsewhere in the codebase.  All pointers have been checked for being null earlier, else that's a bug.
