### ISSUE TITLE
IPv4 redistribution broken in babeld 1.8.1

### ISSUE THREAD

**Issue by niyawe** [jech/babeld#13]
Hi,

it seems like the ipv4 routes aren't announced with babel 1.8.1. I did a git bisect and commit 4f4e3cba796e719b97449f6303961171132f3c74 is the first bad one. After removing the line `filter->src_plen_ge += 96;` from this commit the ipv4 route gets announced again.

in the config I have the line
`redistribute ip 10.222.0.0/16 allow`

my routing table has the entry
`10.222.192.0/21 dev batems proto static scope link`

**Comment by jech** [comment]
Confirmed, investigating.  Thanks for the report.

**Comment by jech** [comment]
Should be fixed in 1ffff57e44a4a507786f5626070d9b1f3e371389.  @boutier, please check, I'd like to release 1.8.2 quickly.

**Comment by boutier** [comment]
Looks correct. Probably the simplest way to fix it.
