### ISSUE TITLE
improve route updates from kernel

### ISSUE THREAD

**Issue by christf** [jech/babeld#20]
Taken from the Mailing List from a mail from @jech 

---
The redistribution code in babeld is very primitive:
  1. the code makes a full route dump whenever something changes and
     computes the difference, rather than receiving incremental deltas
     from the kernel;
  2. it uses a quadratic algorithm to compute the difference.
---

**Comment by jech** [comment]
Point 2 has been adressed -- we now do things properly, in *n log(n)* time.  Point 1 remains.

**Comment by jech** [comment]
Work on this happens on the branch "opimise-redistribute"

**Comment by jech** [comment]
Merged in 0842bb9.  Please test.
