### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by unquietwiki** [jech/babeld#22]
Hey there. I've been trying to make use of this software over the years, and find that the man page documentation on how the routing works needs some clarification. There may also be obsolete options on there as well: the "wired" statement comes to mind. I also don't quite understand how the ge and le tags work on subnet masks; and it looks like "local" applies to the IPs, and not subnets. I'd be happy to help work on this effort, if I had some pointers. Thanks!

**Comment by jech** [comment]
Please feel free to submit patches to improve the documentation.

**Comment by unquietwiki** [comment]
Well, can you please tell me how the gt, lt, and local tags are supposed to
work? If I'm clear on that, I can make a good update. Thanks!

**Comment by jech** [comment]
`le` and `ge` constrain the length of the prefix.  For example

    redistribute ip 0.0.0.0/0 le 0

only applies to the default route (prefix length equal to 0), while

  redistribute ip 0.0.0.0/0 ge 24

only applies to routes with a prefix length 24 or longer.

`local` makes the redistribution rule apply to addresses assigned to interfaces as opposed to routes installed in the kernel routing table.

**Comment by unquietwiki** [comment]
@jech Thanks. One more clarification on ge: when we say longer prefix lengths, do we mean...

- 10.0.0.0/8 ge 8 can include 10.2.0.0/16 ?
- 192.168.12.0/24 ge 16 can include 192.168.0.0/16 ?
- Both? Neither?

**Comment by unquietwiki** [comment]
@jech Thanks on that: that really helps. One more clarification: is there any way at all for declaring a static route; or is that left to the OS? I know you have some source-routing application in this, that hasn't been in my own use cases; but maybe that could apply?

**Comment by jech** [comment]
> One more clarification: is there any way at all for declaring a static
> route; or is that left to the OS?

It's left to the OS.
