### ISSUE TITLE
babeld advertises neighbours route instead of own xroute

### ISSUE THREAD

**Issue by fblaese** [jech/babeld#27]
Since commit d05ec6bfdb05328defb8fe46d7ab45e9853cd6c8, babeld announces it's neighbours route instead of it's own xroute, when the routes are identical.

**For example:**

Routers A, B and C are all connected over the same link.
Routers A and B announce 0.0.0.0/0.
Router C then sees:
- The route from A (identified by router-id) over B
- The route from B over A

Both routes seen by C therefore have higher metric, then they should have (both rxcost 96 -> 192).

It looks like A and B are announcing the wrong route to C.

This happens to all IPv4 routes with identical prefix.
This problem does not occur with IPv6 routes.

**Comment by fblaese** [comment]
After some further investigation, i think i found the issue.

Routes from kernel (which always should be source **un**specific) are imported into xroute with src_plen = 0.
Since the commit in question, standard mapping is used for src_prefix as well, so src_plen has to be set to 96 when the route isn't source specific.

However, it is not set here: https://github.com/jech/babeld/commit/d05ec6bfdb05328defb8fe46d7ab45e9853cd6c8#diff-4d7efdb99ede15dfdd1df529a5e310eaR1100

That's also why the localport output for ipv4 xroute sources uses the ipv6 representation (::ffff:0.0.0.0/0)

**Comment by fblaese** [comment]
I've send a pull request with a fix for what i think is the issue here.
See #28.

**Comment by dtaht** [comment]
thx. I'll give this a try...

**Comment by jech** [comment]
Fixed in #28.
