### ISSUE TITLE
Persist routes across restarts

### ISSUE THREAD

**Issue by mweinelt** [jech/babeld#32]
Currently a restart of babeld will cause all routes in the kernel rt to disappear, breaking routing from/across a node even though connectivity is still available. 

If babeld could leave routes in the kernel intact on restarts this would allow for a more graceful migration during upgrades/rebuilds. That would be immensely helpful.

I'm noticing this alot on my laptop, when my package manager rolls out a new version (often due to rebuilds, because dependencies were bumped) of babeld and does a restart. Through this I loose connectivity for about 15-20 seconds.

**Comment by jech** [comment]
The problem with that is that Babel keeps more information about its routes than what is in the kernel.  Hence, it is not possible to recover Babel's data structures after a restart without keeping at least some additional information.

While it would be possible to do a good approximation of what you suggest, it's a little bit of work, and I'm not going to work on this myself.  I will consider patches that add this kind of functionality.

**Comment by jech** [comment]
Please reopen if you intend to work on this.
