### ISSUE TITLE
Provide 1.8.5 release

### ISSUE THREAD

**Issue by adrianschmutzler** [jech/babeld#37]
Hi,

last 1.8.x release has been quite a while ago, and the bug solved in https://github.com/jech/babeld/commit/f7d8f677deb30c71ca3c5b6fd2415425a32c7cf1 causes me to patch manually in several projects.
Is there a chance for releasing a 1.8.5 just with the current state of the 1.8 stable branch?

Best

Adrian

**Comment by jech** [comment]
Agreed, I'll do that.
