### ISSUE TITLE
Erroneous assignment breaks v4mapped routes, might lead to extremly high cpu usage

### ISSUE THREAD

**Issue by fblaese** [jech/babeld#46]
f8bce04 introduced an assignment to src_plen which breaks v4mapped routes.

This seems to result in wrong comparisons between routes, which leads to redistribution of wrong routes and possibly extremly high cpu usage (on slower cpus like embedded openwrt routers)

The problem (and a possible fix) is described in more detail in this pull request: #45

**Comment by jech** [comment]
This should be fixed in 079bea9568ed5e8ab335d324f8d192099d32246e.  Please reopen if that's not the case.
