### ISSUE TITLE
xroutes generated from local addresses are missing v4mapped src_prefix

### ISSUE THREAD

**Issue by fblaese** [jech/babeld#47]
Routes imported from kernel had an incorrectely set src_prefix/src_plen before the issue was fixed in 68b6c5ec6d38e9d958c7387f171d0380878f67bf

Just like it, src_prefix/src_plen isn't encoded properly for routes generated from local addresses.

This leads to issues if the same route/address is announced by multiple babeld nodes, as the route generated locally and the route received from a neighbour are not equal internally.

**Comment by fblaese** [comment]
local addresses are imported from kernel as addresses, so the v4 mapping of src_prefix/src_plen cannot be done like it is done with prefix in kernel_netlink.c: https://github.com/jech/babeld/blob/d42c1dbdfd6dc836c7b0c8e32657d0be5f0b2b84/kernel_netlink.c#L1359


The addresses are converted to routes in filter_address() inside xroute.c, where plen is set to 128 (correct for both v4 and v6):
https://github.com/jech/babeld/blob/d42c1dbdfd6dc836c7b0c8e32657d0be5f0b2b84/xroute.c#L278-L283

**Comment by dtaht** [comment]
I think I might be seeing this...

**Comment by jech** [comment]
Fixed in 079bea9568ed5e8ab335d324f8d192099d32246e.
