### ISSUE TITLE
feature request: do not mark routes as unreachable when some neighbors fall in failed

### ISSUE THREAD

**Issue by HertzHz** [jech/babeld#59]
I noticed that if a neighbor doesn't response hello packet any more, babeld will mark its routes as unreachable very soon and unblock them after the routes converge again. If a neighbor is exiting normally, babeld will route the traffic to another node in milliseconds. But if the neighbor is exiting unexpectedly, there's an annoying time window and the connection will be timeout and disconnected.
I know this feature is to avoid routing loop, but could please give a option to close this "feature"? I want a high availability network with automatically routing switching.

**Comment by jech** [comment]
Please describe more precisely the behaviour in which babeld behaves badly.
