### ISSUE TITLE
Issues with the Makefile

### ISSUE THREAD

**Issue by MisterDA** [jech/babeld#61]
Currently, the Makefile has two issues.

1. Dependencies on header files are not tracked; which means that if a header is touched, files including this header won't be recompiled. This is fixed by my PR.

2. The ` version.h` file depends on git, but Make doesn't know when a new commit has been made, and then cannot regenerate the file. This leads to `babeld -h` reporting the wrong commit. The scenario is as follow: compile once babeld, make a new commit touching a file that does not depend on `version.h`, run `make`, see `./babeld -h` reporting the old commit id.
A simple fix would be to force the regeneration of `version.h`, but that means that all the compilation units depending on it are recompiled at each run. To fix this new problem, we can add a new compilation unit `version.c, version.h` that would export the version string as a function.

**Comment by adschm** [comment]
Or you just always run "make clean" before building anything after you found out about the problem like I do ...

**Comment by jech** [comment]
> Dependencies on header files are not tracked

A true issue, but not worth introducing extra dependencies — the makefile is supposed to be understandable by people who want to port babeld to non-standard systems (think embedded).  Babeld compiles in a fraction of a second, it's not a big deal to do `make clean && make` whenever you edit a header file.

2. In the absence of a git repository, the `version.h` file is generated from the file `version`; this is included automatically in release tarballs by my release script.  If the build happens outside of git and there is no `version` file, then `babeld -v` returns *unknown*, which is fine with me.

> A simple fix would be to force the regeneration of version.h,

I don't see what problem that would solve.  People who build outside a git checkout would still get the wrong version, unless `version.h` is committed each time — which in turn would make the git history unreadable.

**Comment by MisterDA** [comment]
> The makefile is supposed to be understandable by people who want to
> port babeld to non-standard systems (think embedded).

I think that people porting babeld to non-standard systems have the
background knowledge for understanding a dependency graph.

> Babeld compiles in a fraction of a second, it's not a big deal to do
> `make clean && make` whenever you edit a header file.

babeld does not compile in a fraction of a second on my old Raspberry
Pi, for which I can’t seem to set up a cross-compiler. It’s especially
compiling slowly when I turn sanitizers on. I’ve used [ccache](https://ccache.dev/) to
circumvent this problem.

> In the absence of a git repository

I wasn’t referring to that use case. I’m absolutely fine with what
happens in the release tarball.
Suppose that you’re inside the git repository, commit X. You compile
babeld, and `babeld -V` reports commit X. Now, if you do any change
and recompile babeld *without* cleaning `version.h`, `babeld -V` will
report commit X, and not `X-dirty` or a subsequent Y commit, because
`version.h` isn’t regenerated.

We could add a `extern char *babeld_version;` to `babeld.h`, and have
the Makefile always generate `version.c` containing this variable.
That way, defining the version is postponed to link-time and there
would be no need to recompile the whole `babeld.o` compilation unit.

But the current Makefile is fine if the correct way to use it is `make clean
&& make`. ;)

---

I guess that what I’ve learned from this issue and my PR is that
there’s no way to cleanly write a full-featured Makefile in POSIX Make
(that may be done with GNU/BSD dialects). Make isn’t really good at
what it does, and even when we’re generating Makefiles, Make isn’t
really good at its job either.
