### ISSUE TITLE
feature request: get/set more information at runtime

### ISSUE THREAD

**Issue by PolynomialDivision** [jech/babeld#69]
I'm currently doing that openwrt ubus stuff. And it is working very good for me. I would like to have more control about the filter rules and prefixes I announce at runtime.

I would like to expose your global variables
```c
static struct filter *input_filters = NULL;
static struct filter *output_filters = NULL;
static struct filter *redistribute_filters = NULL;
static struct filter *install_filters = NULL;
```
as output, since they contain the important information I would like to access. Maybe u want to expose them via your webserver, too?

Next step for me is to expose add_filter via our ipc.
For me a function is missing that inserts a filter rule at a specific position.

Maybe u have same interests and can take part of some code part? Otherwise, I can write the code, but I would like to get as much upstream, as I can. ;) So I want to hear your opinion.

**Comment by jech** [comment]
> Next step for me is to expose add_filter via our ipc.

Done in #86.

> For me a function is missing that inserts a filter rule at a specific position.

I suggest we proceed as previously — you start hacking at the code, then we work together on defining an interface that can be merged into babeld mainline.
