### ISSUE TITLE
Do not announce prefix?

### ISSUE THREAD

**Issue by PolynomialDivision** [jech/babeld#70]
If I want to not announce a prefix, I have to add those two config lines:
```
config filter
        option type 'redistribute'
        option ip '2001:xx:xx:xx::/64'
        option local 'true'
        option action 'deny'

config filter 
        option type 'redistribute' 
        option ip '2001:xx:xx:xx::/64' 
        option action 'deny' 
```

If one is missing, the routes shows up at other routers. I do not understand why those two lines are necessary?

**Comment by fblaese** [comment]
babeld uses two sources for generating routes that are announced locally.
On the one hand, babeld announces routes from the route table given in import-table.
Additionally, /128 (/32 respectively) routes are generated for addresses assigned to local interfaces.

These routes are filtered seperately (thats what the "option local 'true'" setting is for), so you have to specify filters for both normal routes (imported from the import-table), as well as for local routes (generated from interface addresses).

**Comment by PolynomialDivision** [comment]
Thanks a lot!
