### ISSUE TITLE
babeld incorrectly handles retraction updates when no next-hop TLV precedes the update TLV

### ISSUE THREAD

**Issue by fblaese** [jech/babeld#71]
This is a follow up to #66.

Babeld still logs quite a lot of "Couldn't parse packet" messages when connecting to a bird peer. This is because bird does not include next hop information in before retractions, while babeld requires them.
(Bird also does not evaluate next-hop information when retracting routes)

This results in error messages here:
https://github.com/jech/babeld/blob/231b2802bfb1314237e36000cdbf115852aef604/message.c#L730-L738

But babeld does indeed evaluate the next-hop when searching for retracting routes, so this check cannot simply be removed for retractions:
https://github.com/jech/babeld/blob/231b2802bfb1314237e36000cdbf115852aef604/route.c#L901
https://github.com/jech/babeld/blob/231b2802bfb1314237e36000cdbf115852aef604/route.c#L143-L147

I've asked on bird-users if they think ignoring next-hop is correct, because I couldn't find any hints about this in RFC 6126.
They replied, that RFC6126bis does indeed say that next-hop is not used in case an update is a retraction, so it looks like this was changed at some point in time.

Should next-hop information be ignored by babeld as well or has there been some significant changes to the babel protocol in RFC6126bis, which makes it incompatible to RFC6126?

**Comment by jech** [comment]
I believe this was fixed in d3734a105394af1f94b900b5100f17a129c242b8.  Please reopen if I'm wrong.

**Comment by fblaese** [comment]
Unfortunately it isn't fixed with this commit. Thats why I have opened this issue in the first place.

The issue here is, that even with d3734a105394af1f94b900b5100f17a129c242b8, it is still checked if a next-hop address is defined. This is a problem for IPv4 routes, because these currently require the next-hop to be explicitly defined by a previous TLV. Because it is possible, that no next-hop address was sent before a retraction, the check shown in the first code snippet leads to a error message after `goto fail` and discards the retraction:
https://github.com/jech/babeld/blob/231b2802bfb1314237e36000cdbf115852aef604/message.c#L730-L738

**Comment by jech** [comment]
Right, I see.  Yes, it's problematic, since we cannot easily find the route being retracted in this case.

**Comment by jech** [comment]
Could you please check the branch `retraction-no-nexthop` and tell me what you think?

b29cb705c3b717a7d5c61719936464438b9a48f0

**Comment by fblaese** [comment]
The code looks good to me.
I've built this version and tried it against a bird router. The "Couldn't parse packet" messages are now gone.

**Comment by jech** [comment]
I've finally used a slightly different fix.

Fixed in 3b4b972.
