### ISSUE TITLE
feature request: smoothly update source's metric.

### ISSUE THREAD

**Issue by Catofes** [jech/babeld#73]
I runing babeld over a public internet with tunnel mode. Everything works fine except that sometimes babeld ignore better route. Here is the example:
![image](https://user-images.githubusercontent.com/3324513/106383112-ec2ac100-63fe-11eb-8d79-6d69d1efd14f.png)
The installed route's metric is much more higher than the third one. 

Then i found out that except the direct-connect routes (refmetric==0), all other routes are unfeasible. Here is the debug log:
![image](https://user-images.githubusercontent.com/3324513/106383206-8e4aa900-63ff-11eb-9428-74134d5ed64e.png)

I believe this is caused by huge network flipping. The latency between Beijing and Hongkong meight be 40ms at noon and 120 ms at night. But babeld only record the minimal metric as Feasible Distance, so the better route will never be select at night. 

Is it possible that the source's metric can grow up slowly when network become lagging?

**Comment by Catofes** [comment]
Emm, the growing metric may cause loop...

What about increase seqno cyclicity?

**Comment by jech** [comment]
A route being unfeasible means that babeld couldn't prove that selecting it won't lead to a loop.  It should send a seqno request in that case, to refresh the loop.  If that doesn't happen, it's a bug somewhere.

What's the output of "killall -USR1 babeld` in the problematic case?

**Comment by OstCollector** [comment]
Is it possible to use EMA of packet loss to compute cost?

**Comment by jech** [comment]
> Is it possible to use EMA of packet loss to compute cost?

We already do so.  It's enabled on wireless links by default, and you may
enable ETX on a given (wired) link by doing

  interface eth0 link-qualty true

and on all links by saying

  default link-quality true

**Comment by jech** [comment]
Please reopen if there's still something missing.
