### ISSUE TITLE
monitor events are send twice?

### ISSUE THREAD

**Issue by PolynomialDivision** [jech/babeld#75]
The neighbour change event is often send twice?
For example you directly get:
```
...
change neighbour fff38c3a80 address fe80::43 if wg_wilgu10 reach ffff ureach 0000 rxcost 1024 txcost 256 cost 256
change neighbour fff38c3a80 address fe80::43 if wg_wilgu10 reach ffff ureach 0000 rxcost 1024 txcost 256 cost 256
...
```

**Comment by jech** [comment]
Yes, a change event can be occasionally sent even when nothing has changed.  Whan babeld recomputes the parameters of a neighbour, it doesn't check if the new values are the same as the old ones, it just sends a change even unconditionally.  You should deal with that in your client code.
