### ISSUE TITLE
Inject routes with different mtu?

### ISSUE THREAD

**Issue by PolynomialDivision** [jech/babeld#77]
Is it possible to specify for routes a different mtu? For example I want to inject the default from a specific gateway with another mtu.

(not sure if I'm allowed to ask here, if u feel that this is spamming your github just let me know)

**Comment by jech** [comment]
Babel is a layer 3 protocol, and should in principle not need MTU information — in a properly setup network, PMTU discovery should work and no tweaking of MTU by the routing protocol should be necessary.

Could you please explain the problem you are trying to solve, so we can think together how to best solve it?

**Comment by PolynomialDivision** [comment]
> Could you please explain the problem you are trying to solve, so we can think together how to best solve it?

I currently play around with segment-routing. ;) I added support on OpenWrt for it. If I encap on the gateway and make tests with my client the downstream iperf3 makes trouble. I have to lower the mtu. I will have a deeper look into the issue, but as a quick workaround I wanted to install certain routes with encap with a different mtu. Basically, I can also just announce a different mtu in my RA or dhcpv6 to my clients and everything works smooth again. It is not a babel problem, so you do not have to be worried. ;)

I will close. Thanks for your help. Any suggestions are welcome.

**Comment by PolynomialDivision** [comment]
> Basically, I can also just announce a different mtu in my RA or dhcpv6 to my clients and everything works smooth again.

Somehow that does not work, but setting up my network config correctly works. ;)
