### ISSUE TITLE
Is there intention to support IPv4 multicast group as well?

### ISSUE THREAD

**Issue by vikpattabi** [jech/babeld#78]
Per the IANA, 224.0.0.111 is also registered for Babel. Thank you!

**Comment by jech** [comment]
Babeld can operate in tandem with PIM in order to provide multicast routing (that's what `reflect-kernel-metric` is for).  Babeld itself does not multicast routing.

**Comment by Takalele** [comment]
Hi @jech, I believe @vikpattabi was pointing out that it should also be possible to establish Babel sessions over IPv4, using the multicast address 224.0.0.111.


[IANA has registered the IPv6 multicast group ff02::1:6 and the IPv4 multicast group 224.0.0.111 for use by the Babel protocol.](https://datatracker.ietf.org/doc/rfc8966/)

Is IPv4 support for session establishment something that might be considered for babeld?

BR
Takalele

**Comment by jech** [comment]
Ah, sorry.

> Is IPv4 support for session establishment something that might be considered for babeld?

We don't see any advantages over using IPv6, since Babel can route both IPv4 and IPv6 even when Babel signalling goes over IPv6.

What problem are you trying to solve?

**Comment by Takalele** [comment]
>We don't see any advantages over using IPv6, since Babel can route both IPv4 and IPv6 even when Babel signalling goes over IPv6.

the key advantage here is full feature parity – kind of amusing, usually it's the lack of IPv6 support that gets pointed out :)

>What problem are you trying to solve?

I'm currently evaluating alternatives to OLSRv1 as the routing protocol for my overlay network, which consists of [tinc](https://tinc-vpn.org/) and WireGuard P2P tunnels. The network spans 12 locations in a full mesh topology and involves three different networking platforms: OPNsense, OpenWrt, and [freeRTR with a DPDK/P4 dataplane](http://www.freertr.org/).

Babel looks very promising on paper, so I started testing its interoperability using [containerlab](https://containerlab.dev/). Unfortunately, babeld and freeRTR don't currently interoperate — further troubleshooting is needed.

Out of curiosity, I also wanted to see if enabling IPv4 sessions in babeld would affect interoperability in any way.

**Comment by jech** [comment]
Oh, I see.  I don't think anyone in the Babel community has evaluated freertr.  We've evaluated the BIRD implementation of Babel (very good) and the FRR implementation (somewhat buggy).

Feel free to ask on the mailing list, <babel@lists.alioth.debian.org>.
