### ISSUE TITLE
Error : Generating IPV6 Address

### ISSUE THREAD

**Issue by MasterSumen3110** [jech/babeld#79]
Greetings everyone. 

I have followed the steps to install babeld. However, after reaching the stage of generating ipv6 address, it does give an error,

ip -6 addr add $(generate-ipv6-address -r)/128 dev wlan1

> generate-ipv6-address: command not found
> Error : inet6 prefix is expected rathen than "/128"

Apologies, as I am still a new in this area. Am I missing any steps here? Thank you.

**Comment by jech** [comment]
The `generate-ip-address` command must be installed, please see https://www.irif.fr/~jch/software/files/.
