### ISSUE TITLE
Check Interfaces in add_interface

### ISSUE THREAD

**Issue by andrew-hoff** [jech/babeld#93]
Is there any reason why you don't call `check_interfaces` [here](https://github.com/jech/babeld/blob/master/interface.c#L95)? Would that not reduce latency when adding a new interface at runtime? A bit of experimentation on my part seems to show reduced latency when I make that change. That having been said, I'm new to this repo, so I might be misinterpreting expected behavior.

**Comment by jech** [comment]
Good catch, fixed in 3d8aec4.  (I'm scheduling an interface check 200ms later, since checking interfaces for each new interface would cause quadratic behaviour at startup.)

**Comment by andrew-hoff** [comment]
Great, thank you!
