### ISSUE TITLE
babeld 1.12.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [jech/babeld#94]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
message.c:503:16: error: member reference base type 'const unsigned char' is not a structure or union
            if(IN6_IS_ADDR_MULTICAST(to))
               ^~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/netinet6/in6.h:301:45: note: expanded from macro 'IN6_IS_ADDR_MULTICAST'
#define IN6_IS_ADDR_MULTICAST(a)        ((a)->s6_addr[0] == 0xff)
                                         ~~~^ ~~~~~~~
message.c:569:16: error: member reference base type 'const unsigned char' is not a structure or union
            if(IN6_IS_ADDR_MULTICAST(to))
               ^~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/netinet6/in6.h:301:45: note: expanded from macro 'IN6_IS_ADDR_MULTICAST'
#define IN6_IS_ADDR_MULTICAST(a)        ((a)->s6_addr[0] == 0xff)
                                         ~~~^ ~~~~~~~
2 errors generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/3256497315/jobs/5347104359
relates to Homebrew/homebrew-core#102969
relates to Homebrew/homebrew-core#113206

**Comment by jech** [comment]
Thanks for the report.  Could you please check that branch `fix-multicast-check` works for you?

  https://github.com/jech/babeld/tree/fix-multicast-check

Just do the following:
```
git remote update
git checkout fix-multicast-check
make
```

**Comment by jech** [comment]
Applied to master.  Please let me know if you test the branch and require a stable branch release.

**Comment by chenrui333** [comment]
sorry for the delay, let me give this another try.

**Comment by chenrui333** [comment]
Works for me, thanks for the fix!
